### ISSUE TITLE
text.Clear() does not clear text

### ISSUE THREAD

**Issue by reetou** [faiface/pixel#118]
I'm playing around with pixel and trying to clear button on left mouse click. What did I miss from tutorial? Here's my code.

basicAtlas := text.NewAtlas(basicfont.Face7x13, text.ASCII)
	basicTxt := text.New(pixel.V(100, 500), basicAtlas)

	basicTxt.WriteString("Yo")
	basicTxt.Draw(win, pixel.IM)

	for !win.Closed() {
		if win.JustPressed(pixelgl.MouseButtonLeft) {
			tree := pixel.NewSprite(spritesheet, treesFrames[rand.Intn(len(treesFrames))])
			trees = append(trees, tree)
			matrices = append(matrices, pixel.IM.Scaled(pixel.ZV, 4).Moved(win.MousePosition()))
			basicTxt.Clear()
		}
		for i, tree := range trees {
			tree.Draw(win, matrices[i])
		}
		win.Update()
	}

**Comment by faiface** [comment]
At first you draw the text on the screen and then you never clear the screen later. That's why the text stays there regardless of your clearing of it or not.

I recommend following [this tutorial on matrices](https://github.com/faiface/pixel/wiki/Moving,-scaling-and-rotating-with-Matrix) which is the first in the series to feature changing things on the screen.

**Comment by reetou** [comment]
Thank you.
