### ISSUE TITLE
Replace `Vec` with interface

### ISSUE THREAD

**Issue by TheAceShinigami** [faiface/pixel#158]
I'm porting a project that used to use ascii graphics over to using pixel. I already have a `Vec` used heavily in the project. If instead of a struct being the user facing part of the library it was an interface I would be able to avoid a lot of ugly meaningless type conversions.

**Comment by faiface** [comment]
Hi!

I'm sorry, but the costs of such change would be much higher than the benefits:

1. Performance. Vector as an interface would involve pointers, a lot of unpredictability, etc.
2. Ughy API. Instead of the nice X, Y fields, we'd get X(), SetX(...), and so on.

Furthermore, this change would only save you conversions from your type to Pixel's, but not vice-versa.

Here's some suggestions on what you can do instead:

1. Have only a small portion of your code interfacing with Pixel. That's the only place where conversions need to occur, so that way you'll have only a few of them.
2. Port all your code to Pixel's vector type.
