### ISSUE TITLE
[question] Why does canvas.Clear use CallNonBlock?

### ISSUE THREAD

**Issue by dnaf** [faiface/pixel#196]
I know this is probably a silly question, but I was wondering why `canvas.Clear` uses `mainthread.CallNonBlock` rather than just `mainthread.Call` ([canvas.go:201](https://github.com/faiface/pixel/blob/749271768b50fed15bd2becb2eeffd653f0c420f/pixelgl/canvas.go#L201)). From what I can tell, the only other place in pixel where `CallNonBlock` is used is in `GLTriangles.Update()` ([gltriangles.go:163](https://github.com/faiface/pixel/blob/9aca3bfe7af365a84d89ddb8c04290f10b9c98d9/pixelgl/gltriangles.go#L163)), which has a comment describing why it is used.

I don't use multiple goroutines in my actual code (aside from the main thread and the one that is spawned by `pixelgl.Run`) and was trying to figure out what was causing my draw calls to be blocked, since most of pixel's code seems to block until complete. This single `CallNonBlock` caused me a good deal of confusion until I figured out what was happening, and I was just wondering why it was there. Thanks!

**Comment by faiface** [comment]
Hi!

I used `CallNonBlock` there simply because it isn't required to block. The main reason for blocking in other code is to prevent race conditions. Often, the code on the main thread and the code in another goroutine will use the same data. That's when the call needs to block, so that the data isn't used concurrently. In the case of `canvas.Clear`, there's no shared data, so there's no reason to block. This (probably?) results in better performance because the clear call can be executed concurrently with your game logic. Hope this explains it :)

Btw,

> was trying to figure out what was causing my draw calls to be blocked

is the blocking causing some problems for you?

**Comment by faiface** [comment]
ping

**Comment by dnaf** [comment]
(Oop, sorry for the late reply!)

> is the blocking causing some problems for you?

I can't recall the specific problem, but I remember being confused as to why my profiler was reporting a function with another (blocking) call as taking a lot more time than it should've, as it was waiting for an earlier `Clear` call to finish. It just caused a little bit of confusion for me until I realized what was happening, and was wondering why canvas.Clear had the only instance of CallNonBlock.

It's not a huge issue, just something that caused me a bit of confusion until I figured it out and took it into account.
