### ISSUE TITLE
how to get sprite's position

### ISSUE THREAD

**Issue by liguoqinjim** [faiface/pixel#20]
how to get sprite's position?

**Comment by faiface** [comment]
Hi!

First things first, Sprite doesn't really have a position per se. It has a matrix. Matrix can move it, rotate it, scale it, whatever.

If you want to find out where the center of the Sprite gets moved with a certain matrix, you can use the `Project` method:

```go
center := sprite.Matrix().Project(pixel.V(0, 0))
```

We are projecting `pixel.V(0, 0)`, since that's the original center of the Sprite (before applying matrix). `Project` returns where that position ends up after applying matrix. So, this might be what you're looking for.

Another way is to have the position in a separate variable, such as `player.pos` and set the correct `Sprite`'s matrix before drawing:

```go
func (p *player) Draw(t pixel.Target) {
    p.sprite.SetMatrix(pixel.IM.Moved(p.pos))
    p.sprite.Draw(t)
}
```

Hope this helps :)

**Comment by liguoqinjim** [comment]
thx.I'm clear now.thank you.

**Comment by faiface** [comment]
Have a good time ;)
