### ISSUE TITLE
Direct draw to Screen without X11 server

### ISSUE THREAD

**Issue by flagadajones** [faiface/pixel#201]
Hi, is it possible to direct draw without  X11 server ?

**Comment by draeron** [comment]
i'm curious to know too, on small device such as the raspberry pi X11 performance are terrible

**Comment by Asday** [comment]
There's another issue thread related to Pi performance, #202 - it seems like there's not sufficient OpenGL support on the Pi, and that's that.

**Comment by faiface** [comment]
Hey guys.

Pixel is using GLFW to interface with windowing which uses X11 or Wayland on Linux. However, it probably would be possible to have a package analogous to PixelGL which would not create a window but would take the whole screen and draw directly to it.

But, as @Asday said, it likely would not fix RPi problems because of the OpenGL support.
