### ISSUE TITLE
SetComposeMethod for IMDraw

### ISSUE THREAD

**Issue by fourst4r** [faiface/pixel#208]
Is Porter-Duff composition a possibility for IMDraw in the future?

**Comment by faiface** [comment]
Hmm, that's an interesting idea. However, I don't know if it is a possibility because IMDraw is kinda vector-based. What I mean is that you don't draw pixels in IMDraw, you construct shapes. Porter-Duff composition makes most sense when composing pixels, so that's why it's available for windows and canvases. But, you can always use an IMDraw in combination with a Canvas to make use of Porter-Duff compositions.

If you have an idea of how to make sense of Porter-Duff in IMDraw, let me know, though :)
