### ISSUE TITLE
How to best draw a shape in different positions?

### ISSUE THREAD

**Issue by skoni** [faiface/pixel#21]
I'm playing around with your library and find it very accessible. The tutorials are nicely written. So, i was trying out `imdraw`, did issue my shape building calls and then wanted to draw my shape at different positions. I was expecting `imd.SetMatrix(m)` to do just that, post transform it, but found out that i have to set the matrix before i call `Push`. Maybe i'm missing the right way to do it, but i find it counter intuitive compared to `Sprite`, which i can easily draw with different transformations.

How i could see this work, without knowing too much about all of this, is that the matrix on the struct that gets set by `SetMatrix` would be used for anchoring and transformations and can be reset anytime, like with `Sprite`. Setting the matrix for the individual shape building calls would then happen via a different method. But then you would have to keep two arrays of the verts around, one of the original and one of the transformed data. To make it work like it is now, i guess, i would create a function to build my shape at the position i want it to have, which would work.

What is you intended way of drawing a shape multiple times with different transformations?

**Comment by faiface** [comment]
Hi, I'm glad to hear you like Pixel!

So, first of all, I admit that this part where `SetMatrix` works differently across different types is a little confusing and I have become fully aware of it recently and I'm actually going to fix it, I will describe how.

But, since I haven't fixed it yet, I'll explain how to get around that right now.

Currently, there's actually a system to how `SetMatrix` works. With an "object types" (like `Sprite`), it transforms the whole object. With "target types" (such as a `Window`, `Canvas`, or `IMDraw`) it sets a matrix by which everything that's drawn to that target will be transformed. Since `IMDraw` is a target, `SetMatrix` transforms objects that are "to be drawn" to the `IMDraw`, which makes moving the already drawn objects hard to do.

What you can do, is that instead of setting the matrix of `IMDraw`, you can set the matrix of a target you are drawing the content of `IMDraw` to, such as a window. That transforms all of the content of `IMDraw` when it's drawn to the window. Like this:

```go
imd := imdraw.New(nil)

// draw some stuff to imd

win.SetMatrix(pixel.IM.Moved(pixel.V(100, 100))
imd.Draw(win)
```

This way, the content of `imd` will be moved by (100, 100) when drawn to the window.

If also want to use a camera, you can chain two matrices together, like this:

```go
win.SetMatrix(imdMatrix.Chain(cameraMatrix))
```

Hope this helps

**Comment by faiface** [comment]
Oh, and I forgot to describe how I'm going to fix this. I'm actually going to make a breaking change, remove `SetMatrix` and `SetColorMask` methods from `Sprite` and replace the simple `sprite.Draw(target)` with `sprite.Draw(target, matrix)` and `sprite.DrawColorMask(target, matrix, mask)`. This drawing signatures can be adopted by `Canvas` and `IMDraw` as well.

**Comment by skoni** [comment]
Thanks for the quick and detailed response. I will try what you suggested. The api change sounds great, to have a common draw signature that allows a matrix.
