### ISSUE TITLE
Hi, can you provide a demo with the game start interface game start button character conversation role movement?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [faiface/pixel#22]
Hi, can you provide a demo with the game start interface game start button character conversation role movement?

**Comment by faiface** [comment]
Hi! I'm not sure I understand what you're exactly asking for. Are you asking for a demo with a game menu? And conversations between characters? Please clarify.

**Comment by Yakumo-Yukari** [comment]
yes

**Comment by faiface** [comment]
It seems rather too large for an example/demo. 

If you take a look at the examples directory, all of them are roughly 200-400 lines of code. This would be much more.

Also, examples should demonstrate library's functionality and not just general game programming techniques.

Perhaps it'd be best if you just described what you're struggling with and we can figure it out. Or you can come up with a simpler demo.

**Comment by faiface** [comment]
ping

**Comment by carbontwelve** [comment]
@faiface , I think what @Yakumo-Yukari is asking for is a demo showing the use of scenes with pixel, e.g intro, settings, game levels, etc. In the past I have had each scene be an object in its own right with a structure similar to:

```
type scene interface {
	Update(dt float64)
        Draw(t pixel.Target)
}
```

It would be nice to see an example of this with Pixel but it it is more to to with game dev theory than the internals of a game engine. Unless you want the game engine to provide scene management tooling.

**Comment by faiface** [comment]
Well, since Pixel is a game library and not a game engine, is does not and will never have anything like a built-in scene functionality. And just as @carbontwelve pointed out with the `interface`, this stuff is not hard to implement. I'd say it's a general game programming exercise and anyone who wants to develop a game should be able to tackle it.

Perhaps I will create a tutorial in the future, that will include this kind of things, but that will be a part of something else too. As @carbontwelve said, I will also consider making it an exercise somewhere :)

Regarding the OP, I don't think a broad example like this belongs here. Sorry.
