### ISSUE TITLE
friendly reminder: latest repo code breaks existing code

### ISSUE THREAD

**Issue by redragonx** [faiface/pixel#24]
Hi again,

```
./Maze-generator.go:50: cannot call non-function imd.Color (type color.Color)
./Maze-generator.go:70: cannot call non-function imd.EndShape (type imdraw.EndShape)
./Maze-generator.go:74: cannot call non-function imd.Color (type color.Color)

```

These were easily fixed after making them a property. You probably know this :) but just a fyi

**Comment by faiface** [comment]
I've decided to include these breaking changes for the v0.6 release (which will hopefully be released this Monday). It's a bit unfortunate, but I felt like these were the right choices and since we're before 1.0, it's still allowed :).

Btw, the complete list of breaking changes (will be included in the release notes) is this:

- Changed `Vec` from `complex128` to a `struct` -> added methods for addition, subtraction. Although this change made addition and subtraction not as nice as they were, it made all other operations harder.

- Changed `IMDraw` properties from methods to fields. Again, I think this is the right choice, because it allows for easy setting and getting of the properties.

Hopefully, there will be no breaking changes after this.

Have a good time ;)
