### ISSUE TITLE
Mixing 2d and 3d

### ISSUE THREAD

**Issue by joeblew99** [faiface/pixel#25]
I write an OpenGL 3d renderer. It's very basic test code.

I am curious if I can use compositor to bring the OpenGL Output into your compositor to have a HUD ?

**Comment by faiface** [comment]
Hi!

I'm not sure I fully understand. So, you have your own OpenGL code, right? And you want to somehow embed it to Pixel? Is that what you're asking? Please clarify!

**Comment by b-rother** [comment]
Not OP, but I think I have the same use-case. I have code that manages its own rendering and at a bare minimum needs just a framebuffer id to render to.

To see if it would even work I modified the code to expose things like GLFW, the glhf frame and framebuffer id. From there I was able to MakeContextCurrent, etc. to get things set up and render to the fb and then render the fb to the window.

That's as far as i got... I tried rendering to fb 0 directly but I think Pixel clears everything when it renders so I wasn't able get Pixel to e.g. draw a line with a transparent background on top of the screen.

The only way I found to render my fb was to render it directly to the screen as opposed to using a canvas and rendering to the window but I just ended up back at square 1 being unable to draw on top of the screen without clearing what's already there.

**Comment by faiface** [comment]
Ok, I never actually thought of these usecases, but here we go.

I've just added `ID` methods to `Texture`, `Shader` and `Frame` objects in GLHF, which return their OpenGL ID. I also added a `Frame` method to `Canvas`, which returns it's underlying `Frame`.

So, this should be enough exposure I guess to prevent you from modifying code :).

A few more things. `Window` has it's underlying `Canvas` and yeah, it clears the screen in each frame and replaces it's content with the content of it's underlying `Canvas`. There's no way to access this `Canvas`, but you can instead create your own and then draw this own `Canvas` to the `Window`.

Another important thing is, that you need to do all OpenGL calls from the main thread, thus, you need to call:

```go
mainthread.Call(func() {
    // OpenGL code
})
```

Otherwise it won't work. And one more thing, don't forget to `Begin` and `End` (bind, unbind) the GLHF objects :).

Hope this helps!

**Comment by b-rother** [comment]
@faiface good call on the mainthread.**Call**, it turns out that I'd been accidentally using mainthread,**Run** in an attempt to run things on the main thread :man_facepalming:. After fixing that and incorporating the new updates, everything is working perfectly. Thanks! :)

**Comment by joeblew99** [comment]
@faiface 
sorry about making an issue that confused.

Yes @b-rother pretty much nailed it, in that we have the same needs.

**Comment by faiface** [comment]
@joeblew99 Cool! Did my previous answer help you or you need some more help?

**Comment by faiface** [comment]
Closing, because no more response from the author.

**Comment by joeblew99** [comment]
@b-rother have you got a sample of the code or can we add this to the examples.

Compositing is really useful feature of pixel because it allows combining things from different sources.

I am going to look into:.
Adding WebKit output.
Adding text editor HUD
Adding instrumentation as a plugin.
