### ISSUE TITLE
typewriter.go example supports unicode.Han? (Chinese, Japanese, Korean)

### ISSUE THREAD

**Issue by NGamma** [faiface/pixel#27]
I'm not sure how to modify your awesome typewriter example to support Asian Characters.
Maybe a function like this will be enough?
`ttfFromFile("chinese_font.TTF", 42),  text.RangeTable(unicode.Han)`
Could you provide a little example?
Thanks!

**Comment by faiface** [comment]
Characters are always retrieved from an Atlas. An Atlas is always created using [text.NewAtlas](https://godoc.org/github.com/faiface/pixel/text#NewAtlas) function which takes a font and sets of runes. As you can see [here](https://github.com/faiface/pixel/blob/master/examples/typewriter/main.go#L257), we're creating an Atlas with ASCII and Latin rune sets, where Latin set is created from `unicode.Latin`. Similarly, you can add `unicode.Han`:

```go
		regular = text.NewAtlas(
			ttfFromBytesMust(goregular.TTF, 42),
			text.ASCII, text.RangeTable(unicode.Latin), text.RangeTable(unicode.Han),
		)
```

Do the same for `bold` and `italic` atlases. You can also remove the Latin support. Beware, that the Atlas creation will take significantly longer (thus app start up time). Also, you might need to lower the text size, because the Atlas texture might grow too big to the point where OpenGL can't hold it.

Also, Pixel (because of GLFW) has no support for IME :(.

**Comment by NGamma** [comment]
I just tested it. Yeah, It freezes while loading and the goregular.TTF does not support japanese so an empty square shows up instead.
It seems that the proper way to go is to load the characters that I need to use individually as sprites.
Anyway, thanks for your FTL response! :)

**Comment by faiface** [comment]
Go Regular doesn't support Han, but if you have a proper font you can use it instead. To load a font, just load the TTF file to a byte slice and then use the `ttfFromBytesMust` function to create a font. You can use it then just like the Go Regular font. No need to use Sprites, it'll work if you use a correct font.
