### ISSUE TITLE
Bitmap rendering could be sped up

### ISSUE THREAD

**Issue by prydin** [faiface/pixel#281]
I'm working on code that dynamically builds a bitmap every frame. I can du this by generating a native Go ```image.RGBA```, then use ```PictureDataFromImage```, turn it into a sprite and draw it to my canvas. Doing that, my pixels are copied at least three times. I could speed it up by building my own ```PictureData``` without taking the extra step via an ```Image```. However, my profiling shows that I still spend a considerable amount of time in ```NewGLPicture```.

I could easily build my image as a flat array of ```uint8``` which could be mapped directly to a Texture.

For this, I propose we either introduce a ```FlatArrayPicture``` type that simply contains a flat array of uint8 that ```NewGLPicture``` can just map to the texture - or - that we expose the underlying ```Texture``` object so code that needs to render bitmaps VERY quickly can access them directly.

I am willing to make this any of these changes in a PR.

**Comment by cebarks** [comment]
I think the functionality you want already exists in [`glhf`](https://github.com/faiface/glhf). Specifically looking at [`glhf.NewTexture()`](https://pkg.go.dev/github.com/faiface/glhf#NewTexture), which allows you to build a new texture from an array of uint8. Not sure how you would render that as opengl confused me to no end. Otherwise, you can access the `glhf.Texture` of a `pixel.Canvas` with the `.Texture()` method.

**Comment by prydin** [comment]
Yeah, I eventually figured that out. There's still a few copies made internally in the code that you probably avoid, but I'm getting the performance I need out of it now, so I'm closing this.
