### ISSUE TITLE
GUI support!

### ISSUE THREAD

**Issue by unreadable** [faiface/pixel#29]
Hey, first of all really nice game library, I like it how easy it's to work with it and the fact that is based on opengl. I'm interested to find out if this library will be GUI compatible in the near future...currently there isn't a stable gui library for go, but I do believe that this library could make a good one ;)

**Comment by faiface** [comment]
Hi! Currently, we're working on finishing the most important features which are described in the [Missing features](https://github.com/faiface/pixel#missing-features) section of the README.

For the future, I have a few ideas on how to make a GUI library and I'll probably make one. However, don't expect that any time soon (soon = a few months).

Btw, what do you  exactly mean by "GUI compatible"?

**Comment by krypton97** [comment]
Maybe gui compatible is the wrong term here, I meant to say gui features, better said. There's some that this library does not provide, but it can be extended instead:)

**Comment by faiface** [comment]
Yeah, GUI features will definitely not be provided by Pixel itself, but by a separate package instead. And it doesn't have to be me who writes that package.

**Comment by joeblew99** [comment]
all,

i use this for golang GUI that uses opengl:
https://github.com/aarzilli/nucular

I have been playing with pixel & https://github.com/hajimehoshi/ebiten too.

I need all 3 aspects in the GUI
- Forms
- 2D
- 3D

Each has their strength:
I think that the way nucular works is pretty good for forms. It uses shiny under the hood.
The way pixel works is great for 2D, but lacks mobile support. But its pure openGL approach means you have good shader access etc.
The way ebiten works is great, and has full mobile support too. It uses shiny under the hood. The way it does mobile support is very very good because it gives you the access to the front end custom stuff as a way out.

So what to do ?
So we have all this great code but it needs unification maybe. Or we can test a compositor so that you can use ebiten as the root and it controls the window, and then you can use nucular & editen and other ones that are out there and composite it into the editen canvas. 

Or a refactoring.. Pixel as i understand it has no mobile support ?

**Comment by hajimehoshi** [comment]
> The way ebiten works is great, and has full mobile support too. It uses shiny under the hood. 

Ebiten doesn't use Shinny. Did you mean gomobile?

**Comment by hajimehoshi** [comment]
BTW I'm against unifying Pixel and Ebiten. They have different philosophy.

**Comment by joeblew99** [comment]
sorry i meant gomobile... good catch :)

Ebiten is really easily my favourite because of the mapping to the gomobile code. 
So maybe i can use framebuffer / compositing to compose a HUD on top that happens to use shiny for example ? This would allow me to use nucular (which uses shiny) for menus, combo, etc etc.

https://github.com/aarzilli/nucular

**Comment by hajimehoshi** [comment]
Not sure about Pixel but Ebiten hides the implementation about framebuffers so it is impossible to use shinny as you suggested.

**Comment by faiface** [comment]
@hajimehoshi Pixel itself has no concept of framebuffer, but PixelGL exposes framebuffers of Canvas. 

Despite that, @joeblew99, I don't think what you're suggesting is really possible, neither it's a good idea. FYI, [Nuklear](https://github.com/vurtun/nuklear) (which Nucular is based on I believe) is completely rendering-backend independed, so with enough work, you can make it work with Pixel or Ebiten. For that, I'd probably rather recommend [golang-ui/nuklear](https://github.com/golang-ui/nuklear) (I haven't tried it).

**Comment by joeblew99** [comment]
@faiface thanks.
i have tried golang-ui/nuklear. 
https://github.com/aarzilli/nucular is pretty compelling as a Forms GUI.
https://github.com/aarzilli/gdlv uses nucular, and extends it further. 
Its impressive. You should try both - really..... Its not as easy to use as pixel and IMDraw helper for sure...

Now, regarding my mad idea of framebuffer compositing. The only reason i suggest it is because it allows to mix Forms, 2d and 3d frameworks together in the same app. There are many reasons why this is a good thing, but in the end its really so that many different rendering tools can be brough together. Kind of like the Linux idea of each thing doing its thing well rather than trying to do everything, which is just boiling the ocean. I guess you can at least why i am suggesting it.

**Comment by Chillance** [comment]
@htrob did this: https://gist.github.com/htrob/7eddea79a8dbe673e5b4d0bb048726b0 which I think is a good starting point.

Also, raylib has some basic ones implemented: https://github.com/gen2brain/raylib-go/tree/master/raygui

Now, what I would like to see is something like you see in the gist there. The "core" of the GUI takes care of lay-outing and positioning. And, you can create your own little widgets easily, while the "core" takes care of that lay-outing and positioning.

**Comment by joeblew99** [comment]
The gist looks good. Thanks !!

The positioning / arrangement is something I too was thinking about with all this.

At the moment I am really trying to work out if I should base everything on ebiten. I am leaning towards it because of its stated support for desktop and mobile.

Then I can get cracking making a GUI lib masked on material components. These need to support all internationalisation aspects. I am also hoping they can be agnostic to the framework they are used within but not too sure if that is too ambitious.

Lastly adding virtual keyboard and cut and paste for mobile to ebiten ( if I use that ) is required for it to be usable.

Would appreciate all advice and can then setup a kitchen sink repo of the GUI controls. I used to build custom hui and do lots of 3d graphics and cgi so I have the stomach for how long it takes to do this type of detailed work :)

**Comment by Chillance** [comment]
Sounds cool. Now, if it was me, I would use that gist and maybe be inspired by https://github.com/golang-ui/nuklear (https://github.com/vurtun/nuklear) and https://github.com/gen2brain/raylib-go and build the whole thing as independent from any rendering as possible. And then add a layer for Pixel.

Meaning, by it self, all logic is there in pure Go. You have a bunch widgets, that can adapt, resize and layout themselves naturally, and possibly is easily theme-able too. It's easy to expand and make your own widgets/controls where you can reuse controls/components too. And then it talks to Pixel to render them.

**Comment by Chillance** [comment]
I also find it fascinating that you seem to be good with 3d graphics. That can certainly help making it look good, which is a VERY important aspect to, as that is what people will see first.

**Comment by joeblew99** [comment]
@Chillance thanks for the links.

I am still playing around with the graphics, and making them vector based so they are scale independent. Ebiten does not have support for vector graphics yet.

**Comment by Chillance** [comment]
That sounds excellent! You don't happen to have a screenshot of something?

And/or anything available I can play around with?

**Comment by rucuriousyet** [comment]
Making a GUI lib for a game shouldn't be that bad... use a R-tree or Quad-tree for mouse input, create your own HBox and VBox layout primitives and some basic inputs (button, input field etc)

**Comment by dusk125** [comment]
There is now a UI library built for Pixel using imgui bindings: [PixelUI](https://github.com/dusk125/pixelui/releases/tag/v0.1.0) I'm going to consider this closed, there is some discussion about adding native UIs, but that's probably not going to be added directly to the Pixel library.
