### ISSUE TITLE
Clearing part of a Batch

### ISSUE THREAD

**Issue by harraps** [faiface/pixel#49]
Not really an issue, but is it possible to clear part of a Batch so that if I remove a block from a tilemap, I wouldn't need to rebuild the whole Batch ?
I am asking that because I want to build a tilemap with transparent parts so that it is possible to superpose multiple tilemaps.

**Comment by faiface** [comment]
This is currently not possible in a straightforward way. You can do that though, here are two ways:

**First way**:
1. Create your own `TrianglesData` and fill it with data.
2. Create a `Drawer` with an appropriate `Picture` for your data.
3. Change the data whenever and call `Dirty` on the `Drawer` when you do that.

This way is actually not much faster than rebuilding batch each time, because `Drawer` will flush all of the data when dirty.

**Second way**:
1. Use `win.MakeTriangles` to get drawable triangles residing directly on the graphics card.
2. Modify it however you want and then call `triangles.Draw(picture)` where `picture` is a picture created with `win.MakePicture`.

This will be as fast as you get probably get it. It's applicable to any `Target`, not just `Window`.

**Comment by harraps** [comment]
Thank you for your answer.
I will try that way.
