### ISSUE TITLE
Camera rotates around ZV, not given position

### ISSUE THREAD

**Issue by bunyk** [faiface/pixel#51]
This is probably not the issue with pixel, and I probably need to ask it somewhere on StackOverflow, but maybe here is more proper place to ask.

 I try to create some space flying simulator. To draw my rocket I use following transformations:

```go
func (r *Rocket) Draw(win *pixelgl.Window) {
        matrix := pixel.IM.Scaled(pixel.ZV, 0.05)
        matrix = matrix.Rotated(pixel.ZV, r.angle - math.Pi / 2) // Let zero angle be pointed up
        matrix = matrix.Moved(r.pos)
        r.sprite.Draw(win, matrix)
}
```

It works fine, I could fly rocket around a screen.

Now I want to put my rocket into the center of the screen pointed up, to simulate view from it. I use this code:

```go
	cam := pixel.IM.
			Moved(pixel.ZV.Sub(rocket.pos)).
			Moved(win.Bounds().Center()).
			Rotated(rocket.pos, -rocket.angle + math.Pi / 2)

	win.SetMatrix(cam)
```

Without rotation it works great, but when I add rotation to compensate rocket rotation, no matter where, and around what vector, for example when I turn rocket left I get this:

![image](https://user-images.githubusercontent.com/244042/30006682-780c9e8e-9106-11e7-9a7b-a491bb7c9a2b.png)

Rocket should be at the location of screen pointed by arrow, but instead is to the left and down, and when it's position is far away from zero vector it gets off the screen. World rotates not around rocket, but around it's zero vector, that is the problem. How to fix this? I tried different order of transformations with no luck. Maybe add this to camera tutorial?

**Comment by faiface** [comment]
When using the matrix operations (move, rotate, etc.) think of it as if you where transforming the whole world.

So, let's take a look at what you're doing:

```go
			Moved(pixel.ZV.Sub(rocket.pos)).
```

First you move the whole world by `-rocket.pos`, which moves the rocket to the `(0, 0)` position. Now, rocket is at the origin.

```go
			Moved(win.Bounds().Center()).
```

Second you move everything by the center of the screen vector. This moves stuff that was at `(0, 0)` to the center of the screen. So, the rocket is now at the center of the screen.

```go
			Rotated(rocket.pos, -rocket.angle + math.Pi / 2)
```

Then, you rotate the world around the original rocket position, but the rocket is no longer there. It's at the center of the screen.

That's why you're not getting what you were expecting.

There are a few ways to solve this.

1. I *think* that rearranging it this way solves it:
```go
			Rotated(rocket.pos, -rocket.angle + math.Pi / 2).
			Moved(pixel.ZV.Sub(rocket.pos)).
			Moved(win.Bounds().Center())
```
2. Rotating around the center of the screen at the end will rotate around the ship, because the ship is there at that point.

**Comment by bunyk** [comment]
Nope. I tried what you suggested. Regardles around what I rotate, everything rotates around start of the carthesian coordinate system. Looks like for `win.SetMatrix` there is no such thing as rotating around point, or I missing something completely obvious.

I'll publish my code in a moment so you could see by yourself.

And thank you for so amazingly quick answer.

**Comment by faiface** [comment]
Alright, I'm playing with your code and I can confirm your reported behaviour. It's weird, I'm trying to figure it out.

**Comment by faiface** [comment]
So, it turned out, there actually was a bug in Pixel. `Matrix.Chained` method chained the matrices in the wrong order and since `Matrix.Rotated` was using it, `Rotated` was wrong too.

I pushed a fix, should work fine now.

**Comment by bunyk** [comment]
Yes, now it works fine. I'm happy to know that my issue was actually useful.

**Comment by faiface** [comment]
Great! Thanks for reporting! It's a shame that such an obvious bug was present in the code for such a long time.
