### ISSUE TITLE
Memory leak with batch := pixel.NewBatch(&pixel.TrianglesData{}, quakeIcon) 	

### ISSUE THREAD

**Issue by xinkiknix** [faiface/pixel#66]
When using batch := pixel.NewBatch(&pixel.TrianglesData{}, quakeIcon) in the for for !win.Closed() {} loop creates a memory leak, I had to move it outside the loop and use batch.Clear() to fix the issue.

**Comment by faiface** [comment]
You are right, there is a memory leak, but it's not a bug and it's documented here: https://godoc.org/github.com/faiface/pixel#Drawer

The memory leak results from a **single object** (sprite, imdraw, ...) being drawn onto an **unbounded number of targets**. Since objects that can be drawn cache information necessary to be drawn onto targets, this causes memory leak.

The solution is to simply avoid drawing one object onto an unbounded number of targets.
