### ISSUE TITLE
Pre-made basic camera

### ISSUE THREAD

**Issue by quillaja** [faiface/pixel#95]
I was thinking that it would be useful to have a basic easy-to-use camera included with pixel, so that the user doesn't have to re-implement basic pan/zoom every time they start a new project. To that end, I made a simple camera based off the way you demonstrate a camera in the tutorials.

If you think this is a good idea, I'll be happy to submit a pull request (I've never done a pull request on github, but I have an understanding of how it works). In the meantime, the [complete code is at this gist](https://gist.github.com/quillaja/7ffbf31c6ca639451d28e3a9c1e366b5). Of course some of the package references will have to be changed if it is included in pixel.

My idea was to make a default instance of Camera essentially ready-to-use with sane defaults that would serve most users, but provide the flexibility to customize the behavior as needed.

The example in Camera's docstring illustrates a basic use case. An example in a full working program can be found in my [fun/attractor repo](https://github.com/quillaja/fun/tree/master/attractor). It's a simple particle physics engine example I've been working on lately.

Let me know what you think. I have some other potential contributions that I may like to work on in the future, but this seemed like an easy but valuable way to start.

**Comment by faiface** [comment]
Hi! I really appreciate your time and effort you put into this, your code and documentation is great! I'm not happy to do that, I have to disappoint you, I don't think this is a good idea. Let me explain why I think so:
1. The use-case is pretty limited as it is tied to PixelGL package. Most games actually don't move cameras using any keys, camera gets moved automatically either according to a character or some "cinematic" camera system.
2. Implementing a camera gives people a very nice introduction to Matrix and makes them understand it quite well. This would take that opportunity from them and as a result would make learning Matrix quite harder and more confusing.
3. Implementing a camera using Matrix is actually just a few lines of code. In the current state, Pixel is very consistent and homogeneous, everything related to movement and spacial transformations is dealt with using a Matrix. No questions like "should I use matrix or camera?".

The first point could be fixed by making the camera PixelGL independent, which could be easily done. The utility would be much higher after that, but there are still points 2 and 3. More appealing would be a more "full-featured" PixelGL independent camera package that would implement all kinds of camera features, but that would be more work.

I'm sorry to reject this contribution, I'll be very glad to accept future contributions, as your code is great. We can talk about what would be beneficial at the Gitter chat.

Thanks anyway!

**Comment by quillaja** [comment]
It's your call, though I disagree with with points 1 and 3. My counter point to 1 is that a 2d graphics library is useful for more than just games. I personally want to use it for explorations of topics like fractals, cellular automata, and other random things where I would like to pan and zoom with mouse and keyboard. And to point 3, the camera I wrote is using matrix fundamentally, and mostly just manages state for you in a nice package.

Anyway, if I have any other contributions, I'll post again.

**Comment by faiface** [comment]
I'll be happy to accept contributions! To avoid situations like this (you do some work and then it gets rejected), I recommend discussing changes on the Gitter channel.
